# Generated by Django 3.2.9 on 2021-11-05 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stanica',
            fields=[
                ('idstanica', models.AutoField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'stanica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vlak',
            fields=[
                ('idvlak', models.AutoField(primary_key=True, serialize=False)),
                ('brvagona', models.IntegerField()),
                ('brputnikavagon', models.IntegerField()),
            ],
            options={
                'db_table': 'vlak',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vlakstanica',
            fields=[
                ('idvlakstanica', models.AutoField(primary_key=True, serialize=False)),
                ('vrijemeDolazak', models.DateTimeField()),
                ('vrijemePolazak', models.DateTimeField()),
                ('kasnjenje', models.TimeField()),
                ('idstanica', models.ForeignKey(db_column='idstanica', on_delete=django.db.models.deletion.DO_NOTHING, to='base.stanica')),
                ('idvlak', models.ForeignKey(db_column='idvlak', on_delete=django.db.models.deletion.DO_NOTHING, to='base.vlak')),
            ],
            options={
                'db_table': 'vlakstanica',
                'managed': True,
                'unique_together': {('idvlak', 'idstanica')},
            },
        ),
        migrations.CreateModel(
            name='Karta',
            fields=[
                ('cijena', models.FloatField()),
                ('idkarta', models.AutoField(primary_key=True, serialize=False)),
                ('vrijemepolaska', models.DateTimeField()),
                ('vrijemedolaska', models.DateTimeField()),
                ('polaziste', models.CharField(max_length=20)),
                ('odrediste', models.CharField(max_length=20)),
                ('idkorisnik', models.ForeignKey(db_column='idkorisnik', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idvlak', models.ForeignKey(db_column='idvlak', on_delete=django.db.models.deletion.CASCADE, to='base.vlak')),
            ],
            options={
                'db_table': 'karta',
                'managed': True,
                'unique_together': {('idkarta', 'idkorisnik', 'idvlak')},
            },
        ),
    ]
