# Generated by Django 3.2.9 on 2021-11-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlakstanica',
            name='vrijemePolazak',
            field=models.TimeField(),
        ),
    ]
