# Generated by Django 3.2.9 on 2021-11-05 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_vlakstanica_vrijemepolazak'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karta',
            old_name='vrijemedolaska',
            new_name='vrijemedolazak',
        ),
        migrations.RenameField(
            model_name='karta',
            old_name='vrijemepolaska',
            new_name='vrijemepolazak',
        ),
        migrations.RenameField(
            model_name='vlakstanica',
            old_name='vrijemeDolazak',
            new_name='vrijemedolazak',
        ),
        migrations.RemoveField(
            model_name='vlakstanica',
            name='vrijemePolazak',
        ),
        migrations.AddField(
            model_name='vlakstanica',
            name='vrijemepolazak',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 0, 0)),
            preserve_default=False,
        ),
    ]
