# Generated by Django 3.2.9 on 2021-11-14 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211105_1816'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vlakstanica',
            unique_together={('idvlak', 'idstanica', 'idvlakstanica')},
        ),
    ]
