# Generated by Django 3.2.9 on 2021-11-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_vlakstanica_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vlakstanica',
            unique_together=set(),
        ),
    ]
