# Generated by Django 3.2.9 on 2021-12-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_vlakstanica_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlakstanica',
            name='kasnjenje',
        ),
    ]
