# Generated by Django 3.2.9 on 2021-12-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_vlakstanica_kasnjenje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlakstanica',
            name='vrijemedolazak',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='vlakstanica',
            name='vrijemepolazak',
            field=models.TimeField(),
        ),
    ]
