# Generated by Django 3.2.9 on 2021-12-27 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20211227_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlak',
            name='idkrajnjastanica',
            field=models.ForeignKey(db_column='idstanica', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='base.stanica'),
        ),
        migrations.AddField(
            model_name='vlak',
            name='kolosijek',
            field=models.IntegerField(default=1),
        ),
    ]
