# Generated by Django 3.2.9 on 2021-12-27 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20211227_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlak',
            name='idkrajnjastanica',
            field=models.ForeignKey(db_column='idkrajnjastanica', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='base.stanica'),
        ),
    ]
