# Generated by Django 3.2.9 on 2022-01-06 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_vlak_idkrajnjastanica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karta',
            name='odrediste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='odrediste', to='base.stanica'),
        ),
        migrations.AlterField(
            model_name='karta',
            name='polaziste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='polaziste', to='base.stanica'),
        ),
    ]
