# Generated by Django 3.2.9 on 2022-01-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20220106_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='karta',
            name='kolosijek',
            field=models.IntegerField(default=1),
        ),
    ]
