# Generated by Django 3.2.9 on 2021-11-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='korisnik',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='korisnik',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='korisnik',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='korisnik',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='korisnik',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='korisnik',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='korisnik',
            name='username',
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='uloga',
            field=models.IntegerField(default=0),
        ),
    ]
