# Generated by Django 3.2.9 on 2021-11-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211107_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='uloga',
        ),
    ]
