# Generated by Django 3.2.9 on 2021-11-17 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_korisnik_brkartice'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='datum_registracije',
            field=models.DateField(default=datetime.datetime(2021, 11, 17, 17, 7, 4, 209669, tzinfo=utc)),
        ),
    ]
