# Generated by Django 3.2.9 on 2021-11-19 16:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_korisnik_datum_registracije'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='datum_registracije',
            field=models.DateField(default=datetime.datetime(2021, 11, 19, 16, 18, 42, 382670, tzinfo=utc)),
        ),
    ]
